# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('dt', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lendingapp.CommonInfo')),
                ('client_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingapp.Client')),
            ],
            bases=('lendingapp.commoninfo',),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lendingapp.CommonInfo')),
                ('category', models.CharField(choices=[('pay', 'Payment'), ('cre', 'Credit'), ('rem', 'Remit'), ('pay', 'Payment'), ('min', 'Misc In'), ('mout', 'Misc Out')], max_length=10)),
                ('bank', models.CharField(choices=[('bdo', 'BDO'), ('bpi', 'BPI')], max_length=10)),
            ],
            bases=('lendingapp.commoninfo',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lendingapp.CommonInfo')),
                ('credit_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingapp.Credit')),
            ],
            bases=('lendingapp.commoninfo',),
        ),
    ]
