# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('dt', models.DateField(verbose_name='date')),
                ('remarks', models.TextField(blank=True)),
                ('clientfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingapp.Client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('dt', models.DateField(verbose_name='date')),
                ('remarks', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Remit', 'Remit'), ('Misc In', 'Misc In'), ('Misc Out', 'Misc Out')], max_length=10)),
                ('bank', models.CharField(blank=True, choices=[('bdo', 'BDO'), ('bpi', 'BPI')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('dt', models.DateField(verbose_name='date')),
                ('remarks', models.TextField(blank=True)),
                ('clientfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingapp.Client', verbose_name='Client')),
                ('creditfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingapp.Credit', verbose_name='Credit')),
            ],
        ),
    ]
