# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='bank',
            field=models.CharField(blank=True, choices=[('bdo', 'BDO'), ('bpi', 'BPI')], max_length=10),
        ),
    ]
