# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendingapp', '0002_auto_20171007_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
