# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lendingapp', '0004_auto_20171007_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='credit_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='payment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='dt',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='client_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingapp.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='category',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Credit', 'Credit'), ('Remit', 'Remit'), ('Payment', 'Payment'), ('Misc In', 'Misc In'), ('Misc Out', 'Misc Out')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingapp.Credit', verbose_name='Credit'),
        ),
    ]
